[package]
name = "ivol"
version = "0.0.2"
edition = "2018"
repository = "https://github.com/maksim07/ivol"
license = "Apache-2.0"

[dependencies]
rv="0.13.1"
nrfind = "1.0.3"
clap="2.33.3"
rand = "0.8.4"

