[package]
name = "ivol"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rv="0.13.1"
nrfind = "1.0.3"
clap="2.33.3"
